cat mobile/src/main/java/com/example/SettingsActivity.kt | awk '
/setContent \{/ {
    print "        setContent {"
    print "            MyApplicationTheme {"
    print "                var apiKey by remember { mutableStateOf(sharedPrefs.getString(\"gemini_api_key\", \"\") ?: \"\") }"
    print "                var modelName by remember { mutableStateOf(sharedPrefs.getString(\"gemini_model_name\", \"gemini-3.5-flash\") ?: \"gemini-3.5-flash\") }"
    print "                var expanded by remember { mutableStateOf(false) }"
    print "                var availableModels by remember { mutableStateOf(listOf(\"gemini-3.5-flash\", \"gemini-3.1-pro-preview\", \"gemini-2.5-flash\")) }"
    print "                var isFetchingModels by remember { mutableStateOf(false) }"
    print "                var isTesting by remember { mutableStateOf(false) }"
    print "                var testResult by remember { mutableStateOf<String?>(null) }"
    print "                var fetchError by remember { mutableStateOf<String?>(null) }"
    print "                val scope = rememberCoroutineScope()"
    print "                "
    print "                LaunchedEffect(apiKey) {"
    print "                    if (apiKey.isNotBlank()) {"
    print "                        isFetchingModels = true"
    print "                        fetchError = null"
    print "                        try {"
    print "                            kotlinx.coroutines.delay(1000)"
    print "                            val models = AiHelper.fetchAvailableModels(apiKey)"
    print "                            if (models.isNotEmpty()) {"
    print "                                availableModels = models"
    print "                                if (!models.contains(modelName)) {"
    print "                                    modelName = models.first()"
    print "                                    sharedPrefs.edit().putString(\"gemini_model_name\", modelName).apply()"
    print "                                }"
    print "                            }"
    print "                        } catch (e: Exception) {"
    print "                            fetchError = e.message"
    print "                        } finally {"
    print "                            isFetchingModels = false"
    print "                        }"
    print "                    }"
    print "                }"
    print "                "
    print "                Scaffold("
    print "                    modifier = Modifier.fillMaxSize(),"
    print "                    containerColor = Color(0xFFF7F2FA),"
    print "                    topBar = {"
    print "                        TopAppBar("
    print "                            title = { Text(\"Settings\", fontSize = 20.sp, fontWeight = FontWeight.Medium, color = Color(0xFF1C1B1F)) },"
    print "                            navigationIcon = {"
    print "                                IconButton(onClick = { finish() }) {"
    print "                                    Icon(Icons.Default.ArrowBack, contentDescription = \"Back\", tint = Color(0xFF1C1B1F))"
    print "                                }"
    print "                            },"
    print "                            colors = TopAppBarDefaults.topAppBarColors(containerColor = Color(0xFFF7F2FA))"
    print "                        )"
    print "                    }"
    print "                ) { padding ->"
    print "                    Column("
    print "                        modifier = Modifier.fillMaxSize().padding(padding).padding(16.dp),"
    print "                        verticalArrangement = Arrangement.spacedBy(16.dp)"
    print "                    ) {"
    print "                        Text(\"AI Integration\", style = MaterialTheme.typography.titleMedium)"
    print "                        OutlinedTextField("
    print "                            value = apiKey,"
    print "                            onValueChange = { apiKey = it; sharedPrefs.edit().putString(\"gemini_api_key\", it).apply() },"
    print "                            label = { Text(\"Gemini API Key\") },"
    print "                            modifier = Modifier.fillMaxWidth(),"
    print "                            visualTransformation = PasswordVisualTransformation(),"
    print "                            singleLine = true,"
    print "                            shape = RoundedCornerShape(16.dp),"
    print "                            colors = OutlinedTextFieldDefaults.colors("
    print "                                focusedBorderColor = Color(0xFF6750A4), unfocusedBorderColor = Color(0xFFCAC4D0),"
    print "                                focusedContainerColor = Color.White, unfocusedContainerColor = Color.White"
    print "                            )"
    print "                        )"
    print "                        ExposedDropdownMenuBox("
    print "                            expanded = expanded,"
    print "                            onExpandedChange = { expanded = it }"
    print "                        ) {"
    print "                            OutlinedTextField("
    print "                                value = modelName,"
    print "                                onValueChange = { modelName = it; sharedPrefs.edit().putString(\"gemini_model_name\", it).apply() },"
    print "                                label = { Text(\"Model Name\") },"
    print "                                modifier = Modifier.fillMaxWidth().menuAnchor(),"
    print "                                singleLine = true,"
    print "                                shape = RoundedCornerShape(16.dp),"
    print "                                colors = OutlinedTextFieldDefaults.colors("
    print "                                    focusedBorderColor = Color(0xFF6750A4), unfocusedBorderColor = Color(0xFFCAC4D0),"
    print "                                    focusedContainerColor = Color.White, unfocusedContainerColor = Color.White"
    print "                                )"
    print "                            )"
    print "                            ExposedDropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {"
    print "                                availableModels.forEach { selectionOption ->"
    print "                                    DropdownMenuItem("
    print "                                        text = { Text(selectionOption) },"
    print "                                        onClick = {"
    print "                                            modelName = selectionOption"
    print "                                            sharedPrefs.edit().putString(\"gemini_model_name\", selectionOption).apply()"
    print "                                            expanded = false"
    print "                                        }"
    print "                                    )"
    print "                                }"
    print "                            }"
    print "                        }"
    print "                        if (isFetchingModels) Text(\"Fetching models...\", color = Color.Gray, style = MaterialTheme.typography.bodySmall)"
    print "                        if (fetchError != null) Text(\"Fetch error: $fetchError\", color = Color.Red, style = MaterialTheme.typography.bodySmall)"
    print "                        "
    print "                        Button("
    print "                            onClick = {"
    print "                                scope.launch {"
    print "                                    isTesting = true; testResult = null"
    print "                                    try {"
    print "                                        testResult = AiHelper.testApiKey(apiKey, modelName)"
    print "                                    } catch (e: Exception) {"
    print "                                        testResult = e.message"
    print "                                    } finally {"
    print "                                        isTesting = false"
    print "                                    }"
    print "                                }"
    print "                            },"
    print "                            enabled = apiKey.isNotBlank() && !isTesting,"
    print "                            modifier = Modifier.fillMaxWidth()"
    print "                        ) {"
    print "                            if (isTesting) CircularProgressIndicator(modifier = Modifier.size(20.dp), color = Color.White) else Text(\"Test Connection\")"
    print "                        }"
    print "                        if (testResult != null) {"
    print "                            Text("
    print "                                text = testResult ?: \"\","
    print "                                color = if (testResult?.startsWith(\"Success\") == true) Color(0xFF4CAF50) else Color.Red,"
    print "                                style = MaterialTheme.typography.bodyMedium"
    print "                            )"
    print "                        }"
    print "                    }"
    print "                }"
    print "            }"
    print "        }"
    print "    }"
    print "}"
    exit
}
{ print $0 }
' > tmp.kt
mv tmp.kt mobile/src/main/java/com/example/SettingsActivity.kt
